// Minimal staging seed: 1 superadmin, 1 school, 1 teacher, 1 class,
// 1 student, 1 worksheet template — just enough to drive read smoke tests.
//
// Run: DATABASE_URL=<staging-url> node prisma/seed-staging.mjs
//
// Idempotent: re-running upserts the same fixed IDs, so smoke scripts can
// hardcode them. Drops a JSON file at prisma/seed-staging.out.json with the
// IDs and credentials so smoke-parity.sh can source it.

import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const IDS = {
  superadmin: '00000000-0000-4000-8000-000000000001',
  teacher:    '00000000-0000-4000-8000-000000000002',
  student:    '00000000-0000-4000-8000-000000000003',
  school:     '00000000-0000-4000-8000-000000000010',
  class:      '00000000-0000-4000-8000-000000000020',
  template:   '00000000-0000-4000-8000-000000000030',
};

const PASSWORD = 'staging-password-1';

async function main() {
  const prisma = new PrismaClient();
  const hash = await bcrypt.hash(PASSWORD, 10);

  // Reset isArchived on every fixture — `POST /api/classes/:id/archive`
  // cascades to students, and the matching unarchive does NOT cascade back,
  // so re-running this script is the canonical way to recover from "where
  // did my student go?" after archive testing.
  await prisma.school.upsert({
    where: { id: IDS.school },
    update: { name: 'Staging School', isArchived: false },
    create: { id: IDS.school, name: 'Staging School' },
  });

  await prisma.user.upsert({
    where: { id: IDS.superadmin },
    update: { username: 'staging_superadmin', name: 'Staging Superadmin', role: 'SUPERADMIN', password: hash, isArchived: false },
    create: { id: IDS.superadmin, username: 'staging_superadmin', name: 'Staging Superadmin', role: 'SUPERADMIN', password: hash },
  });

  await prisma.user.upsert({
    where: { id: IDS.teacher },
    update: { username: 'staging_teacher', name: 'Staging Teacher', role: 'TEACHER', password: hash, isArchived: false },
    create: { id: IDS.teacher, username: 'staging_teacher', name: 'Staging Teacher', role: 'TEACHER', password: hash },
  });

  await prisma.user.upsert({
    where: { id: IDS.student },
    update: { username: 'staging_student', name: 'Staging Student', role: 'STUDENT', password: hash, tokenNumber: 'STAGING-001', isArchived: false },
    create: { id: IDS.student, username: 'staging_student', name: 'Staging Student', role: 'STUDENT', password: hash, tokenNumber: 'STAGING-001' },
  });

  await prisma.class.upsert({
    where: { id: IDS.class },
    update: { name: 'Staging Class', schoolId: IDS.school, isArchived: false },
    create: { id: IDS.class, name: 'Staging Class', schoolId: IDS.school },
  });

  await prisma.teacherSchool.upsert({
    where: { teacherId_schoolId: { teacherId: IDS.teacher, schoolId: IDS.school } },
    update: {},
    create: { teacherId: IDS.teacher, schoolId: IDS.school },
  });
  await prisma.teacherClass.upsert({
    where: { teacherId_classId: { teacherId: IDS.teacher, classId: IDS.class } },
    update: {},
    create: { teacherId: IDS.teacher, classId: IDS.class },
  });
  await prisma.studentSchool.upsert({
    where: { studentId_schoolId: { studentId: IDS.student, schoolId: IDS.school } },
    update: {},
    create: { studentId: IDS.student, schoolId: IDS.school },
  });
  await prisma.studentClass.upsert({
    where: { studentId_classId: { studentId: IDS.student, classId: IDS.class } },
    update: {},
    create: { studentId: IDS.student, classId: IDS.class },
  });
  await prisma.adminSchool.upsert({
    where: { adminId_schoolId: { adminId: IDS.superadmin, schoolId: IDS.school } },
    update: {},
    create: { adminId: IDS.superadmin, schoolId: IDS.school },
  });

  await prisma.worksheetTemplate.upsert({
    where: { id: IDS.template },
    update: { worksheetNumber: 1 },
    create: { id: IDS.template, worksheetNumber: 1 },
  });

  const out = {
    note: 'Generated by prisma/seed-staging.mjs — safe to commit but DO NOT use these IDs/passwords in prod.',
    superadminId: IDS.superadmin,
    teacherId: IDS.teacher,
    studentId: IDS.student,
    schoolId: IDS.school,
    classId: IDS.class,
    templateId: IDS.template,
    superadminUsername: 'staging_superadmin',
    teacherUsername: 'staging_teacher',
    studentUsername: 'staging_student',
    password: PASSWORD,
  };
  const here = dirname(fileURLToPath(import.meta.url));
  writeFileSync(join(here, 'seed-staging.out.json'), JSON.stringify(out, null, 2) + '\n');
  console.log('seeded:', out);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
